//=============================================================================
//	THIS SOURCE CODE IS PROPRIETARY INFORMATION BELONGING TO INTERVIDEO, INC.
// 	ANY USE INCLUDING BUT NOT LIMITED TO COPYING OF CODE, CONCEPTS, AND/OR
//	ALGORITHMS IS PROHIBITED EXCEPT WITH EXPRESS WRITTEN PERMISSION BY THE 
//	COMPANY.
//
// 	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
// 	KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// 	IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
// 	PURPOSE.
//
// 	Copyright (c) 2007 InterVideo Corporation.  All Rights Reserved.
//
//-----------------------------------------------------------------------------

#ifndef _VDO_PARAM_TYPE_H_
#define _VDO_PARAM_TYPE_H_

enum VdoParamType
{
	VDO_PARAM_UNKOWN =0x0000,
		VDO_PARAM_OPERATION_RELEASEFRAME,
		VDO_PARAM_SET_OPEN_OPTION,
		VDO_PARAM_SET_SMART_DECODE,
		VDO_PARAM_SET_NVCTRL_SPEED,
		VDO_PARAM_SET_DOWNSAMPLE,
		VDO_PARAM_SET_EOS,
		VDO_PARAM_SET_DECODER_HURRYUP,
		VDO_PARAM_SET_DISPLAY_STATUS,
		VDO_PARAM_SET_ESTIMATE_NEXT_DISPLAY_TIME,
		VDO_PARAM_GET_CURRENT_IMG_TYPE,
		VDO_PARAM_GET_DISPLAY_IMG_PTS,
		VDO_PARAM_GET_DISPLAY_IMG_INFORMATION,
		VDO_PARAM_GET_DISPLAYABLE_FRAME_NUM,
		VDO_PARAM_SET_HVDSERVICE,
		VDO_PARAM_SET_PERF_BASE_POINTER,
		VDO_PARAM_SET_OPEN_OPTION_EX,
		VDO_PARAM_SET_FAST_SEEKING,
		VDO_PARAM_SET_D3D_SURFACE_SIZE, //useless in H264VDec
		VDO_PARAM_SET_PREDICT_NEXT_SEEKING_COST,
		VDO_PARAM_GET_BYTECOUNT,
		VDO_PARAM_SET_APP_FLAG
};

#endif //_VDO_PARAM_TYPE_H_