#ifndef _TRSDKV1CCONFIGDEF_H_
#define _TRSDKV1CCONFIGDEF_H_

// [ENVMAKE_CONFIG_BEGIN]
// ENVDEF_TRSDK_VERSION
// ENVDEF_EV_iviTR_FNOG_RUN
// ENVDEF_EV_iviTR_FNOG_AUTOFIX_BUILD
// ENVDEF_EV_iviTR_FNOG_VERIFY_MAP
// ENVDEF_EV_iviTR_FNOG_RUN_TREXE
// ENVDEF_EV_iviTR_FNOG_SEED
// ENVDEF_EV_iviTR_FNOG_BACKUP_FOLDER
// [ENVMAKE_CONFIG_END]

//#define ENVDEF_TRSDK_VERSION			1.0
#define ENVDEF_EV_iviTR_FNOG_RUN		1
#define ENVDEF_EV_iviTR_FNOG_AUTOFIX_BUILD	0
#define ENVDEF_EV_iviTR_FNOG_VERIFY_MAP		1
#define ENVDEF_EV_iviTR_FNOG_RUN_TREXE		0
#define ENVDEF_EV_iviTR_FNOG_SEED		302394
//#define ENVDEF_EV_iviTR_FNOG_BACKUP_FOLDER	¡§C:\FnoBackup¡¨

#endif // _TRSDKV1CCONFIGDEF_H_