#ifndef _HIJACKDETECT_DX9_H_
#define _HIJACKDETECT_DX9_H_

#define D3D9_IMAGESIZE	1728512

#define D3D9_OFFSET_ADDREF 1
#define D3D9_OFFSET_RELEASE	2
#define D3D9_OFFSET_RESET 16
#define D3D9_OFFSET_PRESENT 17
#define D3D9_OFFSET_BEGINSCENE 41
#define D3D9_OFFSET_ENDSCENE 42

INT GetDetFuncNumD3D9();
HRESULT LoadDeviceVTableD3D9(LPDWORD pVTableDetect, LPDWORD pDevice);
HRESULT LoadDeviceVTableOffsetD3D9(LPDWORD pVTableOffset, HWND hwnd);

#endif // _UTIL_HIJACKDETECT_DX9_H_