//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Perf2.rc
//
#define IDD_DIALOG1                     102
#define IDD_PROPPAGE_LARGE              107
#define IDD_CUSTOMIZE                   107
#define IDR_TOOLBAR                     121
#define IDD_MERGE                       123
#define IDD_CONTROLDIALOG               124
#define IDR_MAINMENU                    1001
#define ID_CUSTOMIZE_OK                 1005
#define ID_CUSTOMIZE_CANCEL             1006
#define BUFSIZE                         1024
#define IDC_LIST                        1037
#define IDC_LIST2                       1038
#define IDC_AVAILABLELIST               1038
#define IDC_ACTIVELIST                  1039
#define IDC_ADDBUTTON                   1041
#define IDC_REMOVEBUTTON                1042
#define IDC_RESETBUTTON                 1043
#define IDC_CHECKAUDIO                  1044
#define IDC_CHECKVIDEO                  1045
#define IDC_CHECKDEMUX                  1046
#define IDC_CHECKDISPLAY                1047
#define IDC_STATICEVENTTYPE             1048
#define IDC_EDITCUSTOMIZEEVENT          1049
#define IDC_EDITCUSTOMIZEEVENTID        1050
#define IDC_BUTTONADDEVENT              1051
#define IDC_STATICCUSTOMIZEEVENT        1052
#define IDC_RESETBUTTON2                1053
#define IDC_CLEARBUTTON                 1053
#define ID_AUDIO_DECODING_1ST_DATA_EVENT 3001
#define ID_AUDIO_DECODING_2ND_DATA_EVENT 3002
#define ID_AUDIO_BACKEND_1ST_BUFFER_EVENT 3003
#define ID_AUDIO_BACKEND_2ND_BUFFER_EVENT 3004
#define ID_AUDIO_BACKEND_METADATA_BUFFER_EVENT 3005
#define ID_AUDIO_RENDER_BUFFER_EVENT    3006
#define ID_AUDIO_AVSYNC_PTS_DELTA_UPDATE_EVENT 3007
#define ID_DEMUX_VIDEO_EB_EVENT         3008
#define ID_DEMUX_AUDIO_EB_EVENT         3009
#define ID_DEMUX_2ND_VIDEO_EB_EVENT     3010
#define ID_DEMUX_2ND_AUDIO_EB_EVENT     3011
#define ID_DEMUX_PG_EB_EVENT            3012
#define ID_DEMUX_2ND_PG_EB_EVENT        3013
#define ID_DEMUX_IG_EB_EVENT            3014
#define ID_DISPLAY_PREPARE_FRAME_COST_UPDATE_EVENT 3015
#define ID_DISPLAY_DISPLAY_FRAME_COST_UPDATE_EVENT 3016
#define ID_DISPLAY_AVSYNC_UPDATE_EVENT  3017
#define ID_DISPLAY_JITTER_EVENT         3018
#define ID_DISPLAY_FRAME_PTS_DELTA_UPDATE_EVENT 3019
#define ID_DISPLAY_DELTA_UPDATE_EVENT   3020
#define ID_DISPLAY_FRAME_DROP_EVENT     3022
#define ID_DISPLAY_2ND_FRAME_DROP_EVENT 3023
#define ID_DISPLAY_2ND_FRAME_PTS_DELTA_UPDATE_EVENT 3025
#define ID_AUDIO_DECODING_DATA_IN_PTS_DELTA_UPDATE_EVENT 3026
#define ID_AUDIO_DECODING_DATA_OUT_PTS_DELTA_UPDATE_EVENT 3027
#define ID_DEMUX_SECTOR_BUFFER_EVENT    3028
#define ID_DEMUX_DOWNSTREAM_VIDEO_DATA_RATE_UPDATE_EVENT 3029
#define ID_DEMUX_DOWNSTREAM_2ND_VIDE_DATA_RATE_UPDATEO_EVENT 3030
#define ID_DEMUX_DOWNSTREAM_AUDIO_DATA_RATE_UPDATE_EVENT 3031
#define ID_DEMUX_DOWNSTREAM_2ND_AUDIO_DATA_RATE_UPDATE_EVENT 3032
#define ID_DEMUX_DOWNSTREAM_PG_DATA_RATE_UPDATE_EVENT 3033
#define ID_DEMUX_DOWNSTREAM_IG_DATA_RATE_UPDATE_EVENT 3034
#define ID_DEMUX_VIDEO_MB_EVENT         3035
#define ID_DEMUX_2ND_VIDEO_MB_EVENT     3036
#define ID_DEMUX_SECTOR_INDEX_UPDATE_EVENT 3037
#define ID_DEMUX_COUNTER_DISCONTINUITY_EVENT 3038
#define ID_DEMUX_MAIN_PATH_MEDIA_ERROR_EVENT 3039
#define ID_DEMUX_PTS_GAP_EVENT          3040
#define ID_DEMUX_VIDEO_PTS_DELTA_EVENT  3041
#define ID_DEMUX_2ND_VIDEO_PTS_DELTA_EVENT 3042
#define ID_DEMUX_AUDIO_PTS_DELTA_EVENT  3043
#define ID_DEMUX_2ND_AUDIO_PTS_DELTA_EVENT 3044
#define ID_DEMUX_VIDEO_SRC_DELTA_EVENT  3045
#define ID_DEMUX_2ND_VIDEO_SRC_DELTA_EVENT 3046
#define ID_DEMUX_AUDIO_SRC_DELTA_EVENT  3047
#define ID_DEMUX_2ND_AUDIO_SRC_DELTA_EVENT 3048
#define ID_VIDEO_BITRATE_UPDATE_EVENT   3049
#define ID_VIDEO_2ND_BITRATE_UPDATE_EVENT 3050
#define ID_VIDEO_2ND_FRAME_DROP_EVENT   3054
#define ID_DYNMENU_BASE                 5000
#define ID_VIEWS_VIDEO                  40012
#define ID_VIEWS_QA                     40013
#define ID_VIEWS_MERGE                  40014
#define ID_MERGE_CHECKBOX               40015
#define ID_VIEWS_SAVE                   40017
#define ID_Menu                         40018
#define ID_Views_Default                40020
#define ID_VIEWS_DEFAULT                40024
#define ID_VIEWS_LOAD                   40025
#define ID_EXIT                         40026
#define ID_BUTTON40035                  40035
#define ID_VIEWS_SAVE40037              40037
#define ID_SAVE_DD                      40038
#define ID_SAVE_DD40039                 40039
#define ID_WINDOWS_SELECT               40041
#define ID_WINDOWS                      40042
#define ID_WINDOWS_RESET                40044

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         40045
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
