#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 
//
//   fxc /T ps_3_0 /Fh ColumnInterleavedStereo_ps.h -E
//    MergeSxSColumnInterleaved_PS ColumnInterleavedStereo.psh
//
//
// Parameters:
//
//   sampler2D texture0;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   texture0     s0       1
//

    ps_3_0
    def c0, 2, -2, 0, 0
    dcl_texcoord v0
    dcl vPos.x
    dcl_2d s0
    cmp r0.x, vPos.x, c0.x, c0.y
    rcp r0.y, r0.x
    mul r0.y, r0.y, vPos.x
    frc r0.y, r0.y
    mul r0.x, r0.x, r0.y
    texld r1, v0, s0
    texld r2, v0.zwzw, s0
    cmp oC0, -r0_abs.x, r2, r1

// approximately 8 instruction slots used (2 texture, 6 arithmetic)
#endif

const DWORD g_ps30_MergeSxSColumnInterleaved_PS[] =
{
    0xffff0300, 0x001ffffe, 0x42415443, 0x0000001c, 0x00000053, 0xffff0300, 
    0x00000001, 0x0000001c, 0x20000100, 0x0000004c, 0x00000030, 0x00000003, 
    0x00000001, 0x0000003c, 0x00000000, 0x74786574, 0x30657275, 0xababab00, 
    0x000c0004, 0x00010001, 0x00000001, 0x00000000, 0x335f7370, 0x4d00305f, 
    0x6f726369, 0x74666f73, 0x29522820, 0x44334420, 0x53203958, 0x65646168, 
    0x6f432072, 0x6c69706d, 0x00207265, 0x05000051, 0xa00f0000, 0x40000000, 
    0xc0000000, 0x00000000, 0x00000000, 0x0200001f, 0x80000005, 0x900f0000, 
    0x0200001f, 0x80000000, 0x90011000, 0x0200001f, 0x90000000, 0xa00f0800, 
    0x04000058, 0x80010000, 0x90001000, 0xa0000000, 0xa0550000, 0x02000006, 
    0x80020000, 0x80000000, 0x03000005, 0x80020000, 0x80550000, 0x90001000, 
    0x02000013, 0x80020000, 0x80550000, 0x03000005, 0x80010000, 0x80000000, 
    0x80550000, 0x03000042, 0x800f0001, 0x90e40000, 0xa0e40800, 0x03000042, 
    0x800f0002, 0x90ee0000, 0xa0e40800, 0x04000058, 0x800f0800, 0x8c000000, 
    0x80e40002, 0x80e40001, 0x0000ffff
};
