#if 0
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
//   fxc /T ps_2_0 /Fh LumaKeying_0_255.h -E LumaKeying_0_255_PS LumaKeying.psh
//
//
// Parameters:
//
//   float4 luma;
//   sampler2D texture0;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   luma         c0       1
//   texture0     s0       1
//

    ps_2_0
    def c1, 76.2450027, 149.684998, 29.0699997, 0
    dcl t0.xy
    dcl_2d s0
    texld r0, t0, s0
    dp3 r1.w, r0, c1
    mov oC0, r0
    add r0.xy, -r1.w, c0
    mul r0, r0.y, r0.x
    texkill r0

// approximately 6 instruction slots used (1 texture, 5 arithmetic)
#endif

const DWORD g_ps20_LumaKeying_0_255_PS[] =
{
    0xffff0200, 0x002dfffe, 0x42415443, 0x0000001c, 0x0000007f, 0xffff0200, 
    0x00000002, 0x0000001c, 0x20000100, 0x00000078, 0x00000044, 0x00000002, 
    0x00020001, 0x0000004c, 0x00000000, 0x0000005c, 0x00000003, 0x00020001, 
    0x00000068, 0x00000000, 0x616d756c, 0xababab00, 0x00030001, 0x00040001, 
    0x00000001, 0x00000000, 0x74786574, 0x30657275, 0xababab00, 0x000c0004, 
    0x00010001, 0x00000001, 0x00000000, 0x325f7370, 0x4d00305f, 0x6f726369, 
    0x74666f73, 0x29522820, 0x534c4820, 0x6853204c, 0x72656461, 0x6d6f4320, 
    0x656c6970, 0x2e392072, 0x392e3332, 0x322e3934, 0x00383733, 0x05000051, 
    0xa00f0001, 0x42987d71, 0x4315af5c, 0x41e88f5c, 0x00000000, 0x0200001f, 
    0x80000000, 0xb0030000, 0x0200001f, 0x90000000, 0xa00f0800, 0x03000042, 
    0x800f0000, 0xb0e40000, 0xa0e40800, 0x03000008, 0x80080001, 0x80e40000, 
    0xa0e40001, 0x02000001, 0x800f0800, 0x80e40000, 0x03000002, 0x80030000, 
    0x81ff0001, 0xa0e40000, 0x03000005, 0x800f0000, 0x80550000, 0x80000000, 
    0x01000041, 0x800f0000, 0x0000ffff
};
